{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syslog
  labels:
    {{- include "rsyslog.labels" . | nindent 4 }}
spec:
  {{- if .Values.pvc.storageClassOverride }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }}
{{- end }}
